site_name: CSP Security Services Best Practices
repo_name: sepand/sepand.github.io
repo_url: https://github.com/sepand/sepand.github.io
docs_dir: 'docs/en'
copyright: 'Copyright &copy; Sepand'
site_author: 'Sepand'
site_url: 'https://sepand.github.io/sepand.github.io'
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - tabs
    - content.code.copy
    - announce.dismiss
    - header.autohide
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: switch to light mode

nav:
  - Home: index.md
  - AWS Best Practices: guides/aws/index.md
  - Azure Best Practices: guides/azure/index.md

plugins:
    - search
