site_name: CSP Security Services Best Practices
repo_name: sepand/security-services-best-practices
repo_url: https://github.com/sepand/security-services-best-practices
docs_dir: 'docs/en'
copyright: 'Copyright &copy; Sepand'
site_author: 'Sepand'
site_url: 'https://sepand.github.io/security-services-best-practices'
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - tabs
    - content.code.copy
    - announce.dismiss
    - header.autohide
    - content.code.select
    - content.code.annotate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: switch to light mode

nav:
  - Home: index.md
  - AWS Best Practices: guides/aws/index.md
  - Azure Best Practices: guides/azure/index.md

plugins:
    - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
