## https://squidfunk.github.io/mkdocs-material/
site_name: CSP Security Services Best Practices
repo_name: sepand/security-services-best-practices
repo_url: https://github.com/sepand/sepand.github.io
docs_dir: 'docs/en'
copyright: 'Copyright &copy; Sepand'
site_author: 'Sepand'
site_url: 'https://sepand.github.io'
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle
  features:
    - tabs
    - content.code.copy
    - announce.dismiss
    - header.autohide
    - content.code.select
    - content.code.annotate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: switch to light mode

plugins:
    - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - AWS: 
    - guides/aws/index.md
    - IAM: guides/aws/iam.md
  
  - Azure Best Practices: guides/azure/index.md
